#!/bin/bash
clear
echo "
██      ██ ███    ██ ██    ██ ██   ██     ███████ ██   ██  █████  ██████  ███████ ██ ████████ 
██      ██ ████   ██ ██    ██  ██ ██      ██      ██   ██ ██   ██ ██   ██ ██      ██    ██    
██      ██ ██ ██  ██ ██    ██   ███       ███████ ███████ ███████ ██████  █████   ██    ██    
██      ██ ██  ██ ██ ██    ██  ██ ██           ██ ██   ██ ██   ██ ██   ██ ██      ██    ██    
███████ ██ ██   ████  ██████  ██   ██     ███████ ██   ██ ██   ██ ██   ██ ███████ ██    ██"
sleep 2


echo     "      _____________________________________________________________________"
echo     "     |                                                                     |"
echo     "     |       'Connect Your Wifi Into A Receving Device Hostpot'            |" 
echo     "     |_____________________________________________________________________|"
echo     "     |"
echo     "     |"
echo     "     |" 
echo     "     |"
echo -e  "     Connected your wife press enter to continue... \c"
read
echo 

echo -e "\t\t ------------------ Only Sending not Receiving any files -------------------\n"




echo -e "\n_____________________________Below see your files_____________________________";

echo "";
echo "";
  


ls -1




echo "";
echo "";
echo "____________________________________________________________________________________";



echo 
echo -n "See above your files and enter the sharing your file name with absolutely:";
read filename



#check file is exists...
if [ -e $filename ]
then
echo
echo "your file is copy to a  -> '/var/www/sender' directory. so wait..."
cp -r $filename /var/www/html/sender
sleep 1
echo -e "\n ifconfig is running...\n"
ifconfig
echo -e "\n\n ============================= Important ===================================================="


echo -e "\t'First see above and Copy your wlan0 inet address,
       \n\t and paste the inet ip address on the receving device brower to download the files.'
\n\n\t example your 'wlan0 ip address is ( 192.10.42:33 )' this ip address is enter the receving
\n\t device browser use to get your files."

echo "===================================================================================================="


echo "task is completed...."
sleep 1
echo "good byeee"
echo 
else
echo -e "\n---------------File Not Found-----------------\n"
exit
fi

